name: Security

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1"
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  osv:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.4
    with:
      scan-args: |-
        --recursive
        ./

  scorecard:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: scorecard.sarif
